### ISSUE TITLE
Speed E false positive

### ISSUE THREAD

**Issue by DontNeedAName** [funkemunky/Kauri#46]
Basically if you sprint jump through a horde of mobs it will flag, because of entity collisions and possibly also knockback.

**Comment by GatitoUwU** [comment]
Something to add: Also falses when you walk on ice or something that speeds up your motion.

**Comment by funkemunky** [comment]
Thanks for the report! I had a feeling entity collisions would be an issue. Fixed in following commits https://github.com/funkemunky/Kauri/commit/fd66ba6ee7f9e01b314abf6df1de0f6132cf6284#diff-63f4f44ba4f78a97a02877af2398b6a713da3afe351819708af9bc602fde9d69 
https://github.com/funkemunky/Kauri/commit/427b87c13547c04a8e398c0da9affa57f7c053f7
